#Spring Profile은 어플리케이션 설정을 특정 환경에서만
#적용되게 하거나 환경별 (local,devlop,pro)로 다르게 적용할 때 사용 !
spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
#kakao api를 springboot에서 사용하기
kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    #마리아디비 드라이버
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: common

---
spring:
  config:
    activate:
      on-profile: prod